#-------------------------------------------------------------------------------
# Prints help message
#-------------------------------------------------------------------------------
.PHONY: help
help:
	@echo "make d: Creates documentation"
	@echo "make clean"


.PHONY: d
d:
	asciidoctor *.adoc

.PHONY: clean
clean:
	rm *.html
