# spreadsheetkit/base:1

FROM debian:8.0
MAINTAINER Rino Jose "rjose@spreadsheetkit.com"

RUN apt-get update

RUN apt-get install -y erlang-base
RUN apt-get install -y erlang-inets
RUN apt-get install -y erlang-lager

WORKDIR /release
